# An example Trunk.toml with all possible fields along with their defaults.

[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "static"
# The public URL from which assets are to be served.
public_url = "/"
# Whether to include hash values in the output file names.
filehash = false

[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = []
# Paths to ignore.
ignore = []

[tools]
wasm_bindgen = "0.2.83"

[serve]
# The address to serve on.
address = "127.0.0.1"
# The port to serve on.
port = 8000
# Open a browser tab once the initial build is complete.
open = false
# Disable auto-reload of the web app.
no_autoreload = true

[clean]
# The output dir for all final assets.
dist = "static"
# Optionally perform a cargo clean.
cargo = false

